//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export class FlightSearchRequest {
    originLocationCode!: string;
    destinationLocationCode!: string;
    departureDate!: string;
    returnDate!: string | null;
    adults!: number;
    children!: number;
    infants!: number;
    travelClass!: string | null;
    includedAirlineCodes!: string | null;
    excludedAirlineCodes!: string | null;
    nonStop!: boolean;
    currencyCode!: string | null;
    maxPrice!: number;
    max!: number;

    init(_data?: any) {
        if (_data) {
            this.originLocationCode = _data["originLocationCode"] !== undefined ? _data["originLocationCode"] : <any>null;
            this.destinationLocationCode = _data["destinationLocationCode"] !== undefined ? _data["destinationLocationCode"] : <any>null;
            this.departureDate = _data["departureDate"] !== undefined ? _data["departureDate"] : <any>null;
            this.returnDate = _data["returnDate"] !== undefined ? _data["returnDate"] : <any>null;
            this.adults = _data["adults"] !== undefined ? _data["adults"] : <any>null;
            this.children = _data["children"] !== undefined ? _data["children"] : <any>null;
            this.infants = _data["infants"] !== undefined ? _data["infants"] : <any>null;
            this.travelClass = _data["travelClass"] !== undefined ? _data["travelClass"] : <any>null;
            this.includedAirlineCodes = _data["includedAirlineCodes"] !== undefined ? _data["includedAirlineCodes"] : <any>null;
            this.excludedAirlineCodes = _data["excludedAirlineCodes"] !== undefined ? _data["excludedAirlineCodes"] : <any>null;
            this.nonStop = _data["nonStop"] !== undefined ? _data["nonStop"] : <any>null;
            this.currencyCode = _data["currencyCode"] !== undefined ? _data["currencyCode"] : <any>null;
            this.maxPrice = _data["maxPrice"] !== undefined ? _data["maxPrice"] : <any>null;
            this.max = _data["max"] !== undefined ? _data["max"] : <any>null;
        }
    }

    static fromJS(data: any): FlightSearchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new FlightSearchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["originLocationCode"] = this.originLocationCode !== undefined ? this.originLocationCode : <any>null;
        data["destinationLocationCode"] = this.destinationLocationCode !== undefined ? this.destinationLocationCode : <any>null;
        data["departureDate"] = this.departureDate !== undefined ? this.departureDate : <any>null;
        data["returnDate"] = this.returnDate !== undefined ? this.returnDate : <any>null;
        data["adults"] = this.adults !== undefined ? this.adults : <any>null;
        data["children"] = this.children !== undefined ? this.children : <any>null;
        data["infants"] = this.infants !== undefined ? this.infants : <any>null;
        data["travelClass"] = this.travelClass !== undefined ? this.travelClass : <any>null;
        data["includedAirlineCodes"] = this.includedAirlineCodes !== undefined ? this.includedAirlineCodes : <any>null;
        data["excludedAirlineCodes"] = this.excludedAirlineCodes !== undefined ? this.excludedAirlineCodes : <any>null;
        data["nonStop"] = this.nonStop !== undefined ? this.nonStop : <any>null;
        data["currencyCode"] = this.currencyCode !== undefined ? this.currencyCode : <any>null;
        data["maxPrice"] = this.maxPrice !== undefined ? this.maxPrice : <any>null;
        data["max"] = this.max !== undefined ? this.max : <any>null;
        return data;
    }
}

export class FlightSearchViewModel {
    departureAirport!: string | null;
    departureDate!: string | null;
    arrivalAirport!: string | null;
    arrivalDate!: string | null;
    numberOfPlaneChanges!: string | null;
    numberOfPassengers!: string | null;
    totalPrice!: string | null;
    currency!: string | null;
    departureCarrier!: string | null;
    arrivalCarrier!: string | null;

    init(_data?: any) {
        if (_data) {
            this.departureAirport = _data["departureAirport"] !== undefined ? _data["departureAirport"] : <any>null;
            this.departureDate = _data["departureDate"] !== undefined ? _data["departureDate"] : <any>null;
            this.arrivalAirport = _data["arrivalAirport"] !== undefined ? _data["arrivalAirport"] : <any>null;
            this.arrivalDate = _data["arrivalDate"] !== undefined ? _data["arrivalDate"] : <any>null;
            this.numberOfPlaneChanges = _data["numberOfPlaneChanges"] !== undefined ? _data["numberOfPlaneChanges"] : <any>null;
            this.numberOfPassengers = _data["numberOfPassengers"] !== undefined ? _data["numberOfPassengers"] : <any>null;
            this.totalPrice = _data["totalPrice"] !== undefined ? _data["totalPrice"] : <any>null;
            this.currency = _data["currency"] !== undefined ? _data["currency"] : <any>null;
            this.departureCarrier = _data["departureCarrier"] !== undefined ? _data["departureCarrier"] : <any>null;
            this.arrivalCarrier = _data["arrivalCarrier"] !== undefined ? _data["arrivalCarrier"] : <any>null;
        }
    }

    static fromJS(data: any): FlightSearchViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new FlightSearchViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["departureAirport"] = this.departureAirport !== undefined ? this.departureAirport : <any>null;
        data["departureDate"] = this.departureDate !== undefined ? this.departureDate : <any>null;
        data["arrivalAirport"] = this.arrivalAirport !== undefined ? this.arrivalAirport : <any>null;
        data["arrivalDate"] = this.arrivalDate !== undefined ? this.arrivalDate : <any>null;
        data["numberOfPlaneChanges"] = this.numberOfPlaneChanges !== undefined ? this.numberOfPlaneChanges : <any>null;
        data["numberOfPassengers"] = this.numberOfPassengers !== undefined ? this.numberOfPassengers : <any>null;
        data["totalPrice"] = this.totalPrice !== undefined ? this.totalPrice : <any>null;
        data["currency"] = this.currency !== undefined ? this.currency : <any>null;
        data["departureCarrier"] = this.departureCarrier !== undefined ? this.departureCarrier : <any>null;
        data["arrivalCarrier"] = this.arrivalCarrier !== undefined ? this.arrivalCarrier : <any>null;
        return data;
    }
}